FROM node:boron

RUN apt update && apt install git
WORKDIR /usr/src
RUN git clone https://github.com/MDSLab/wstun
WORKDIR /usr/src/wstun
RUN npm install


CMD ["node", "bin/wstun", "-r", "-s", "8080", "--ssl=false"]