#! /bin/bash
#COUNT

if [ "$#" -ne 1 ]; then
    echo "start-stocat COUNT"
    exit 1
fi

if [ "$1" -eq 1 ]; then
    echo "COUNT cannot be 1"
    exit 1
fi

COUNT=$1

IFACE="gre-lr$COUNT"
ip link del $IFACE
