#! /bin/bash

if [ "$#" -ne 1 ]; then
    echo "start-stocat COUNT"
    exit 1
fi

if [ "$1" -eq 1 ]; then
    echo "COUNT cannot be 1"
    exit 1
fi

COUNT=$1
PORT=`expr $COUNT + 10000`

PID=$(ps aux | grep socat | grep $PORT | awk '{print $2}')
kill -9 $PID
