#!/bin/sh

echo "Uninstalling..."
rm_check=
echo -n "Do you want to keep IoTronic home (/var/lib/iotronic) ? (yes/no) "
read rm_check

if [ "$rm_check" = "no" ]; then

    rm -rf /var/lib/iotronic/

else
	echo "--> IoTronic home is save!"
fi
