#! /bin/bash
#PORT IP
if [ "$#" -ne 2 ]; then
    echo "start-stocat PORT IPTUN"
    exit 1
fi

PORT=$1
IP=$2

#PORT="5000"
#IP="10.0.0.5/24"

set -o verbose

TUNNAME="soc"$PORT
socat -d -d TCP:localhost:$PORT,reuseaddr,forever,interval=10 TUN:$IP,tun-name=$TUNNAME,up &
